from setuptools import setup, find_packages

setup(
    name="scpair",
    version="0.1.0",
    description="scPair: boosting single cell multimodal analysis by leveraging implicit feature selection and single cell atlases",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Hongru Hu, Gerald Quon",
    author_email="hrhu@ucdavis.edu",
    license="MIT",
    packages=find_packages(),
    python_requires=">=3.10,<3.13",
    install_requires=[
        "numpy>=1.21.0",
        "pandas>=1.3.0",
        "scipy>=1.7.0",
        "scikit-learn>=1.0.0",
        "matplotlib>=3.5.0",
        "seaborn>=0.11.0",
        "plotly>=5.0.0",
        "scanpy>=1.8.0",
        "anndata>=0.8.0",
        "torch>=2.0.0",
        "torchvision>=0.15.0",
        "triton>=2.0.0,<3.0.0",
        "tqdm>=4.60.0",
        "jupyter>=1.0.0",
        "ipywidgets>=7.6.0",
    ],
    extras_require={
        "cuda": [
            "torch==2.0.1",
            "torchaudio==2.0.2",
            "torchmetrics==1.3.2",
            "torchvision==0.15.2",
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Scientific/Engineering :: Bio-Informatics",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Operating System :: OS Independent",
    ],
    keywords="single-cell,multimodal,scRNA-seq,ATAC-seq,deep-learning,bioinformatics,genomics,machine-learning,neural-networks",
    project_urls={
        "Homepage": "https://github.com/quon-titative-biology/scPair",
        "Repository": "https://github.com/quon-titative-biology/scPair",
        "Documentation": "https://github.com/quon-titative-biology/scPair/blob/main/tutorials/README.md",
        "Bug Tracker": "https://github.com/quon-titative-biology/scPair/issues",
    },
)
